<?php

require_once dirname(__FILE__) . '/../OrderedLinkedList.php';

/**
 * Test class for OrderedLinkedList.
 * Generated by PHPUnit on 2013-03-03 at 18:44:27.
 */
class OrderedLinkedListTest extends PHPUnit_Framework_TestCase {

    /**
     * @var OrderedLinkedList
     */
    protected $object;

    /**
     * Sets up the fixture, for example, opens a network connection.
     * This method is called before a test is executed.
     */
    protected function setUp() {
        $this->object = new OrderedLinkedList;
    }

    /**
     * Tears down the fixture, for example, closes a network connection.
     * This method is called after a test is executed.
     */
    protected function tearDown() {
        
    }

    /**
     * @todo Implement testOrderedinsert().
     */
    public function testOrderedinsert() {
        $this->object->orderedinsert(3);
        $this->object->orderedinsert(1);
        $this->object->orderedinsert(5);
        $this->object->orderedinsert(2);
        $this->object->orderedinsert(4);
        $this->object->goBegin();
        $this->assertEquals(1,$this->object->getElement());
        $this->object->forward();
        $this->assertEquals(2,$this->object->getElement());
        $this->object->forward();
        $this->assertEquals(3,$this->object->getElement());
        $this->object->forward();
        $this->assertEquals(4,$this->object->getElement());
        $this->object->forward();
        $this->assertEquals(5,$this->object->getElement());
    }

}

?>
